---
abstract: 'TIFF image file support for Imager'
author:
  - 'Tony Cook <tonyc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Imager: 0.94
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 0
  Imager: 0.94
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-File-TIFF
no_index:
  directory:
    - t
    - inc
requires:
  Imager: 0.94
  XSLoader: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Imager
  homepage: http://imager.perl.org/
  repository: git://git.imager.perl.org/imager.git
version: 0.89
